import { PropsWithChildren } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

export const colors = { ink: '#18241E', muted: '#758078', green: '#315D38', lime: '#D4ED55', background: '#F6F7F3', line: '#E7EBE4' };
export function ScreenTitle({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: React.ReactNode }) { return <View style={s.header}><View>{eyebrow ? <Text style={s.eyebrow}>{eyebrow}</Text> : null}<Text style={s.title}>{title}</Text></View>{action}</View>; }
export function Card({ children, style }: PropsWithChildren<{ style?: object }>) { return <View style={[s.card, style]}>{children}</View>; }
export function PrimaryButton({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [s.button, pressed && { opacity: .75 }]}><Text style={s.buttonText}>{label}</Text></Pressable>; }
export function Field({ label, value, onChangeText, placeholder, keyboardType = 'default' }: { label: string; value: string; onChangeText: (text: string) => void; placeholder?: string; keyboardType?: 'default' | 'numeric' }) { return <View style={s.field}><Text style={s.fieldLabel}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#9CA59E" keyboardType={keyboardType} style={s.input} /></View>; }
const s = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end' }, eyebrow: { color: '#758078', fontSize: 10, fontWeight: '900', letterSpacing: 1.1, marginBottom: 5 }, title: { color: '#18241E', fontSize: 30, letterSpacing: -1, fontWeight: '800' }, card: { backgroundColor: '#FFF', borderRadius: 19, padding: 16, borderWidth: 1, borderColor: '#E7EBE4' }, button: { minHeight: 52, borderRadius: 16, justifyContent: 'center', alignItems: 'center', backgroundColor: '#D4ED55' }, buttonText: { color: '#17311B', fontWeight: '900', fontSize: 15 }, field: { gap: 7 }, fieldLabel: { color: '#637068', fontSize: 11, fontWeight: '800' }, input: { minHeight: 48, backgroundColor: '#F6F7F3', borderRadius: 12, paddingHorizontal: 13, color: '#18241E', fontSize: 14 } });
